name: Beta Vendor Deployment
on:
  push:
    branches:
      - main
      - master

jobs:
  web-deploy:
    name: Deploying
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v2

      - name: Composer package cache
        uses: actions/cache@v2
        with:
          path: ./vendor
          key: prod-composer-${{ hashFiles('composer.lock') }}
          restore-keys: |
            prod-composer-
      - name: Composer package install
        run: composer install

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /public-digidocu/vendor/
          port: 21
          local-dir: vendor/
